# Generated by Django 6.0.6 on 2026-06-06 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm_admin', '0004_campaginmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('married_status', models.CharField(max_length=20)),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('pan_number', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('previous_policy', models.CharField(default='No', max_length=5)),
                ('previous_policy_number', models.CharField(blank=True, max_length=50, null=True)),
                ('same_policy', models.CharField(blank=True, max_length=5, null=True)),
                ('agent_feedback', models.TextField(blank=True, null=True)),
                ('campaign_feedback', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_admin.agentmodel')),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_admin.campaginmodel')),
            ],
        ),
    ]
