# Generated by Django 6.0.6 on 2026-06-06 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientmodel',
            old_name='campaign',
            new_name='campagin',
        ),
    ]
