# Generated by Django 6.0.6 on 2026-06-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_rename_campaign_clientmodel_campagin'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='client/'),
        ),
    ]
