# Generated by Django 6.0.6 on 2026-06-08 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_clientmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='address',
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='job',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='clientmodel',
            name='qulification',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='previous_policy',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='same_policy',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
