# Generated by Django 6.0.6 on 2026-06-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmodel',
            name='Agent_ID',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
