# Generated by Django 6.0.6 on 2026-06-06 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0003_alter_agentmodel_agent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaginModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('ctype', models.TextField()),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('stime', models.TimeField()),
                ('etime', models.TimeField()),
                ('location', models.CharField(max_length=100)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_admin.agentmodel')),
            ],
        ),
    ]
