# Generated by Django 6.0.6 on 2026-06-07 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0004_campaginmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentmodel',
            old_name='address',
            new_name='specialization',
        ),
        migrations.RemoveField(
            model_name='agentmodel',
            name='Agent_ID',
        ),
        migrations.RemoveField(
            model_name='agentmodel',
            name='department',
        ),
        migrations.RemoveField(
            model_name='agentmodel',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='agentmodel',
            name='gender',
        ),
    ]
