# Generated by Django 6.0.6 on 2026-06-07 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_admin', '0005_rename_address_agentmodel_specialization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaginmodel',
            old_name='edate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='campaginmodel',
            old_name='ctype',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='campaginmodel',
            old_name='etime',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='campaginmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='campaginmodel',
            name='sdate',
        ),
        migrations.RemoveField(
            model_name='campaginmodel',
            name='stime',
        ),
        migrations.RemoveField(
            model_name='campaginmodel',
            name='title',
        ),
    ]
